#!/bin/ksh
#
# $Id: buildmatrix,v 0.4 2002-08-31 16:22:15 psy Exp $
# ------------------------------------------------------------------------------
#
# Usage:
#   buildmatrix stoplist numstop minlen maxlen maxline local global numfactors estring corpus
#
# This program builds the LSA matrix.

ME=`basename $0`
USAGE="Usage: $ME stoplist numstop minlen maxlen maxline local global numfactors estring corpus"

#
#       Process the command line
#
if (($# != 10))
then
        echo "$USAGE"
        exit 1
fi

STOPLIST=$1
NUMSTOP=$2
MINLEN=$3
MAXLEN=$4
MAXLINE=$5
LOCAL=$6
GLOBAL=$7
NUMFACT=$8
ESTRING=$9
shift
CORPUS=$9

if [ "$GLOBAL" = "none" ]
then
    GLOBAL=""
fi

echo "Building term-document matrix..."
pindex \
    -n $NUMFACT \
    -l $MINLEN \
    -m $MAXLEN \
    -c $STOPLIST \
    -nc $NUMSTOP \
    -e $ESTRING \
    -w $LOCAL $GLOBAL \
    $CORPUS \
    > pindex1.out 2>&1
echo "Performing SVD..."
pindex -D -P $CORPUS \
    > pindex2.out 2>&1
echo "Indexing corpus..."
indexdoc $CORPUS
