#!/u/psy/bin/ksh
#
# $Id: getallreps,v 0.3 2002-08-31 16:22:15 psy Exp $
# ------------------------------------------------------------------------------
#
# Get the most representative sentence from each segment
#
# Usage:
#
# getallreps < corpus.rep
#
# where corpus.rep is a newline-delimited list of topic boundaries

read FROM
read TO
echo 1
while [ $? -eq 0 ]
do
    representative $FROM $TO
    FROM=$TO
    read TO
done
