#!/u/psy/bin/ksh
#
# getallreps.ksh $Revision: 0.2 $ $Date: 2002-08-26 12:03:11 $
# --------------
#
# Get the most representative sentence from each segment
#
# Usage:
#
# getallreps.ksh < corpus.rep
#
# where corpus.rep is a newline-delimited list of topic boundaries

read FROM
read TO
echo 1
while [ $? -eq 0 ]
do
    representative.ksh $FROM $TO
    FROM=$TO
    read TO
done
