#!/usr/bin/perl
#
# gettopicindices.pl $Revision: 0.1 $ $Date: 2002-08-26 12:03:11 $
# ------------------
#
# Usage:
#  gettopicindices.pl
#
# This script takes the output of Freddy Choi's C99 and returns
# a list of DU indices which begin topic boundaries

$i=1;
foreach $line (<>) {
  if ($line eq "==========\n")
    {
     print STDOUT "$i\n";
    }
  else {
    $i++;
  }
}

