#!/usr/bin/perl
#
# $Id: gettopicindices,v 0.2 2002-08-31 16:22:15 psy Exp $
# ------------------------------------------------------------------------------
#
# Usage:
#  gettopicindices
#
# This script takes the output of Freddy Choi's C99 and returns
# a list of DU indices which begin topic boundaries

$i=1;
foreach $line (<>) {
  if ($line eq "==========\n")
    {
     print STDOUT "$i\n";
    }
  else {
    $i++;
  }
}

