#!/bin/ksh
#
# $Id: printsummary,v 0.4 2002-08-31 16:22:16 psy Exp $
# -----------------------------------------------------------------------------
#
# Usage:
#  printsummary corpus < corpus.sumindex
#
# Prints summary given a list of DUs

FMT=fmt

# Usage instructions
ME=`basename $0`
USAGE="Usage: $ME [options] corpus

    -version   print version information
    -s         suppress single-spacing
    -f         suppress formatting
"

#
#       Process the command line
#
if [ $# -lt 1 ]
then
        echo "$USAGE"
        exit 1
fi

while [ $# -gt 0 ]
do
    case $1 in
    -f)        NOFORMAT=1               ;;
    -s)        NOSPACING=1;             ;;
    -\?)       echo "$USAGE"; exit 0    ;;
    --\?)      echo "$USAGE"; exit 0    ;;
    -help)     echo "$USAGE"; exit 0    ;;
    --help)    echo "$USAGE"; exit 0    ;;
    -version)  echo '$Id: printsummary,v 0.4 2002-08-31 16:22:16 psy Exp $'; exit 0    ;;
    --version) echo '$Id: printsummary,v 0.4 2002-08-31 16:22:16 psy Exp $'; exit 0    ;;
    -*)        echo "$ME: invalid argument \"$1\""; exit 1 ;;
    *)         if [ -n "$CORPUS" ]
	       then
		    echo "$USAGE"
		    exit 1
	       fi
	       CORPUS=$1 ;;
    esac
    shift
done

# Make sure corpus is specified
if [ -z "$CORPUS" ]
then
    echo "$ME: no corpus file specified"
    exit 1
fi

# Make sure file is there
if [ ! -e $CORPUS ]
then
    echo "$ME: $CORPUS not found"
    exit 1
fi


read DU

while [ $? -eq 0 ]
do
    getdoc $CORPUS $DU >> ps1.$$
    read DU
done

CMDLINE="cat ps1.$$"

if [ -z "$NOSPACING" ]
then
    CMDLINE="$CMDLINE | singlespace"
fi

if [ -z "$NOFORMAT" ]
then
    CMDLINE="$CMDLINE | $FMT"
fi

eval $CMDLINE

rm ps1.$$ 

