#! /bin/tcsh -f
#
# $Id: singlespace,v 0.2 2002-08-31 16:22:16 psy Exp $
# ------------------------------------------------------------------------------
#
# Undoes double-spacing in a file (assumes even-numbered lines are
# always blank)

sed 'n;d' $1
