#!/usr/bin/perl
#
# $Id: txt2parcorpus,v 0.3 2002-08-27 19:38:44 psy Exp $
# -----------------------------------------------------------------------------
#
# Usage:
#    txt2parcorpus.pl
#
# This script converts a plain ASCII text file for use with ICE.
# It collapses all whitespace and inserts a blank line between
# paragraphs.

$prev = 0;

foreach $line (<>) {
  chop($line);
  if ($line !~ /^\s*$/) {

    # Assume indentation means this is a new paragraph
    $line =~ s/^\s+/\n\n/;

    # Print line
    print STDOUT $line . " ";
    $prev = 1;
  }
  elsif ($prev == 1) {
    print STDOUT "\n\n";
    $prev = 0;
  }
}
